<?php

namespace ContainerGBx0qtL;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_T46Vie9Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.t46Vie9' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.t46Vie9'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'emp' => ['privates', '.errored..service_locator.t46Vie9.Symfony\\Component\\Security\\Core\\User\\UserInterface', NULL, 'Cannot autowire service ".service_locator.t46Vie9": it references interface "Symfony\\Component\\Security\\Core\\User\\UserInterface" but no such service exists. Did you create a class that implements this interface?'],
            'empresa' => ['privates', '.errored..service_locator.t46Vie9.Symfony\\Component\\Security\\Core\\User\\UserInterface', NULL, 'Cannot autowire service ".service_locator.t46Vie9": it references interface "Symfony\\Component\\Security\\Core\\User\\UserInterface" but no such service exists. Did you create a class that implements this interface?'],
            'empresaRepository' => ['privates', 'App\\Repository\\EmpresaRepository', 'getEmpresaRepositoryService', true],
        ], [
            'emp' => 'Symfony\\Component\\Security\\Core\\User\\UserInterface',
            'empresa' => 'Symfony\\Component\\Security\\Core\\User\\UserInterface',
            'empresaRepository' => 'App\\Repository\\EmpresaRepository',
        ]);
    }
}
