<?php

namespace ContainerGBx0qtL;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_GWZl3PQService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.gWZl3PQ' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.gWZl3PQ'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'cliente' => ['privates', '.errored..service_locator.gWZl3PQ.App\\Entity\\Cliente', NULL, 'Cannot autowire service ".service_locator.gWZl3PQ": it references class "App\\Entity\\Cliente" but no such service exists.'],
            'clienteRepository' => ['privates', 'App\\Repository\\ClienteRepository', 'getClienteRepositoryService', true],
            'empresa' => ['privates', '.errored..service_locator.gWZl3PQ.Symfony\\Component\\Security\\Core\\User\\UserInterface', NULL, 'Cannot autowire service ".service_locator.gWZl3PQ": it references interface "Symfony\\Component\\Security\\Core\\User\\UserInterface" but no such service exists. Did you create a class that implements this interface?'],
        ], [
            'cliente' => 'App\\Entity\\Cliente',
            'clienteRepository' => 'App\\Repository\\ClienteRepository',
            'empresa' => 'Symfony\\Component\\Security\\Core\\User\\UserInterface',
        ]);
    }
}
