<?php

namespace ContainerGBx0qtL;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_25pKLxcService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.25pKLxc' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.25pKLxc'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'detalleRepository' => ['privates', 'App\\Repository\\DetalleRepository', 'getDetalleRepositoryService', true],
            'empresa' => ['privates', '.errored..service_locator.25pKLxc.Symfony\\Component\\Security\\Core\\User\\UserInterface', NULL, 'Cannot autowire service ".service_locator.25pKLxc": it references interface "Symfony\\Component\\Security\\Core\\User\\UserInterface" but no such service exists. Did you create a class that implements this interface?'],
            'pedido' => ['privates', '.errored..service_locator.25pKLxc.App\\Entity\\Pedido', NULL, 'Cannot autowire service ".service_locator.25pKLxc": it references class "App\\Entity\\Pedido" but no such service exists.'],
        ], [
            'detalleRepository' => 'App\\Repository\\DetalleRepository',
            'empresa' => 'Symfony\\Component\\Security\\Core\\User\\UserInterface',
            'pedido' => 'App\\Entity\\Pedido',
        ]);
    }
}
