<?php

namespace ContainerGBx0qtL;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCliente2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.MqkMtZc.App\Entity\Cliente' shared service.
     *
     * @return \App\Entity\Cliente
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.MqkMtZc": it references class "App\\Entity\\Cliente" but no such service exists.');
    }
}
