<?php

namespace ContainerGBx0qtL;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPedido2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.EnTD9ox.App\Entity\Pedido' shared service.
     *
     * @return \App\Entity\Pedido
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.EnTD9ox": it references class "App\\Entity\\Pedido" but no such service exists.');
    }
}
