<?php

namespace ContainerKfaTC7z;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getDetalleRepositoryService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Repository\DetalleRepository' shared autowired service.
     *
     * @return \App\Repository\DetalleRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Repository\\DetalleRepository'] = new \App\Repository\DetalleRepository(($container->services['doctrine'] ?? $container->getDoctrineService()));
    }
}
