<?php

namespace ContainerKfaTC7z;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getDetalleTypeService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Form\DetalleType' shared autowired service.
     *
     * @return \App\Form\DetalleType
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Form\\DetalleType'] = new \App\Form\DetalleType();
    }
}
