<?php

namespace ContainerKfaTC7z;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getEmpresa2Service extends App_KernelProdContainer
{
    /*
     * Gets the private '.errored..service_locator.mT1e0jA.App\Entity\Empresa' shared service.
     *
     * @return \App\Entity\Empresa
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.mT1e0jA": it references class "App\\Entity\\Empresa" but no such service exists.');
    }
}
