<?php

namespace Container9ODEsus;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getDetalle3Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.seEimki.App\Entity\Detalle' shared service.
     *
     * @return \App\Entity\Detalle
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.seEimki": it references class "App\\Entity\\Detalle" but no such service exists.');
    }
}
