<?php

namespace Container9ODEsus;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getEmpresaService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.f9r8_yo.App\Entity\Empresa' shared service.
     *
     * @return \App\Entity\Empresa
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.f9r8_yo": it references class "App\\Entity\\Empresa" but no such service exists.');
    }
}
