<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerKfaTC7z\App_KernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerKfaTC7z/App_KernelProdContainer.php') {
    touch(__DIR__.'/ContainerKfaTC7z.legacy');

    return;
}

if (!\class_exists(App_KernelProdContainer::class, false)) {
    \class_alias(\ContainerKfaTC7z\App_KernelProdContainer::class, App_KernelProdContainer::class, false);
}

return new \ContainerKfaTC7z\App_KernelProdContainer([
    'container.build_hash' => 'KfaTC7z',
    'container.build_id' => 'a0c43ecb',
    'container.build_time' => 1653032653,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerKfaTC7z');
