<?php

// This file has been auto-generated by the Symfony Cache Component.

return [[

'App__Entity__Cliente__CLASSMETADATA__' => 0,
'App__Entity__Detalle__CLASSMETADATA__' => 1,
'App__Entity__Empresa__CLASSMETADATA__' => 2,
'App__Entity__Pedido__CLASSMETADATA__' => 3,
'App__Entity__Producto__CLASSMETADATA__' => 4,

], [

0 => static function () {
    return \Symfony\Component\VarExporter\Internal\Hydrator::hydrate(
        $o = [
            clone (($p = &\Symfony\Component\VarExporter\Internal\Registry::$prototypes)['Doctrine\\ORM\\Mapping\\ClassMetadata'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\ClassMetadata')),
            clone ($p['Doctrine\\ORM\\Id\\IdentityGenerator'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Id\\IdentityGenerator')),
        ],
        null,
        [
            'stdClass' => [
                'name' => [
                    'App\\Entity\\Cliente',
                ],
                'namespace' => [
                    'App\\Entity',
                ],
                'rootEntityName' => [
                    'App\\Entity\\Cliente',
                ],
                'customRepositoryClassName' => [
                    'App\\Repository\\ClienteRepository',
                ],
                'identifier' => [
                    [
                        'id',
                    ],
                ],
                'generatorType' => [
                    4,
                ],
                'fieldMappings' => [
                    [
                        'id' => [
                            'fieldName' => 'id',
                            'type' => 'integer',
                            'scale' => null,
                            'length' => null,
                            'unique' => false,
                            'nullable' => false,
                            'precision' => null,
                            'id' => true,
                            'columnName' => 'id',
                        ],
                        'nombre' => [
                            'fieldName' => 'nombre',
                            'type' => 'string',
                            'scale' => null,
                            'length' => 100,
                            'unique' => false,
                            'nullable' => false,
                            'precision' => null,
                            'columnName' => 'nombre',
                        ],
                        'apellidos' => [
                            'fieldName' => 'apellidos',
                            'type' => 'string',
                            'scale' => null,
                            'length' => 100,
                            'unique' => false,
                            'nullable' => false,
                            'precision' => null,
                            'columnName' => 'apellidos',
                        ],
                        'direccion' => [
                            'fieldName' => 'direccion',
                            'type' => 'string',
                            'scale' => null,
                            'length' => 200,
                            'unique' => false,
                            'nullable' => false,
                            'precision' => null,
                            'columnName' => 'direccion',
                        ],
                        'telefono' => [
                            'fieldName' => 'telefono',
                            'type' => 'integer',
                            'scale' => null,
                            'length' => null,
                            'unique' => false,
                            'nullable' => false,
                            'precision' => null,
                            'columnName' => 'telefono',
                        ],
                        'correoElectronico' => [
                            'fieldName' => 'correoElectronico',
                            'type' => 'string',
                            'scale' => null,
                            'length' => 100,
                            'unique' => false,
                            'nullable' => false,
                            'precision' => null,
                            'columnName' => 'correo_electronico',
                        ],
                        'dni' => [
                            'fieldName' => 'dni',
                            'type' => 'string',
                            'scale' => null,
                            'length' => 9,
                            'unique' => false,
                            'nullable' => false,
                            'precision' => null,
                            'columnName' => 'dni',
                        ],
                    ],
                ],
                'fieldNames' => [
                    [
                        'id' => 'id',
                        'nombre' => 'nombre',
                        'apellidos' => 'apellidos',
                        'direccion' => 'direccion',
                        'telefono' => 'telefono',
                        'correo_electronico' => 'correoElectronico',
                        'dni' => 'dni',
                    ],
                ],
                'columnNames' => [
                    [
                        'id' => 'id',
                        'nombre' => 'nombre',
                        'apellidos' => 'apellidos',
                        'direccion' => 'direccion',
                        'telefono' => 'telefono',
                        'correoElectronico' => 'correo_electronico',
                        'dni' => 'dni',
                    ],
                ],
                'table' => [
                    [
                        'name' => 'cliente',
                    ],
                ],
                'associationMappings' => [
                    [
                        'pedidos' => [
                            'fieldName' => 'pedidos',
                            'mappedBy' => 'cliente',
                            'targetEntity' => 'App\\Entity\\Pedido',
                            'cascade' => [],
                            'orphanRemoval' => false,
                            'fetch' => 2,
                            'type' => 4,
                            'inversedBy' => null,
                            'isOwningSide' => false,
                            'sourceEntity' => 'App\\Entity\\Cliente',
                            'isCascadeRemove' => false,
                            'isCascadePersist' => false,
                            'isCascadeRefresh' => false,
                            'isCascadeMerge' => false,
                            'isCascadeDetach' => false,
                        ],
                        'empresa' => [
                            'fieldName' => 'empresa',
                            'joinColumns' => [
                                [
                                    'name' => 'empresa_id',
                                    'referencedColumnName' => 'id',
                                ],
                            ],
                            'cascade' => [],
                            'inversedBy' => 'clientes',
                            'targetEntity' => 'App\\Entity\\Empresa',
                            'fetch' => 2,
                            'type' => 2,
                            'mappedBy' => null,
                            'isOwningSide' => true,
                            'sourceEntity' => 'App\\Entity\\Cliente',
                            'isCascadeRemove' => false,
                            'isCascadePersist' => false,
                            'isCascadeRefresh' => false,
                            'isCascadeMerge' => false,
                            'isCascadeDetach' => false,
                            'sourceToTargetKeyColumns' => [
                                'empresa_id' => 'id',
                            ],
                            'joinColumnFieldNames' => [
                                'empresa_id' => 'empresa_id',
                            ],
                            'targetToSourceKeyColumns' => [
                                'id' => 'empresa_id',
                            ],
                            'orphanRemoval' => false,
                        ],
                    ],
                ],
                'idGenerator' => [
                    $o[1],
                ],
            ],
        ],
        $o[0],
        []
    );
},
1 => static function () {
    return \Symfony\Component\VarExporter\Internal\Hydrator::hydrate(
        $o = [
            clone (($p = &\Symfony\Component\VarExporter\Internal\Registry::$prototypes)['Doctrine\\ORM\\Mapping\\ClassMetadata'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\ClassMetadata')),
            clone ($p['Doctrine\\ORM\\Id\\IdentityGenerator'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Id\\IdentityGenerator')),
        ],
        null,
        [
            'stdClass' => [
                'name' => [
                    'App\\Entity\\Detalle',
                ],
                'namespace' => [
                    'App\\Entity',
                ],
                'rootEntityName' => [
                    'App\\Entity\\Detalle',
                ],
                'customRepositoryClassName' => [
                    'App\\Repository\\DetalleRepository',
                ],
                'identifier' => [
                    [
                        'id',
                    ],
                ],
                'generatorType' => [
                    4,
                ],
                'fieldMappings' => [
                    [
                        'id' => [
                            'fieldName' => 'id',
                            'type' => 'integer',
                            'scale' => null,
                            'length' => null,
                            'unique' => false,
                            'nullable' => false,
                            'precision' => null,
                            'id' => true,
                            'columnName' => 'id',
                        ],
                        'Cantidad' => [
                            'fieldName' => 'Cantidad',
                            'type' => 'integer',
                            'scale' => null,
                            'length' => null,
                            'unique' => false,
                            'nullable' => false,
                            'precision' => null,
                            'columnName' => 'cantidad',
                        ],
                        'precio' => [
                            'fieldName' => 'precio',
                            'type' => 'float',
                            'scale' => null,
                            'length' => null,
                            'unique' => false,
                            'nullable' => false,
                            'precision' => null,
                            'columnName' => 'precio',
                        ],
                    ],
                ],
                'fieldNames' => [
                    [
                        'id' => 'id',
                        'cantidad' => 'Cantidad',
                        'precio' => 'precio',
                    ],
                ],
                'columnNames' => [
                    [
                        'id' => 'id',
                        'Cantidad' => 'cantidad',
                        'precio' => 'precio',
                    ],
                ],
                'table' => [
                    [
                        'name' => 'detalle',
                    ],
                ],
                'associationMappings' => [
                    [
                        'pedido' => [
                            'fieldName' => 'pedido',
                            'joinColumns' => [
                                [
                                    'name' => 'pedido_id',
                                    'referencedColumnName' => 'id',
                                ],
                            ],
                            'cascade' => [],
                            'inversedBy' => 'detalles',
                            'targetEntity' => 'App\\Entity\\Pedido',
                            'fetch' => 2,
                            'type' => 2,
                            'mappedBy' => null,
                            'isOwningSide' => true,
                            'sourceEntity' => 'App\\Entity\\Detalle',
                            'isCascadeRemove' => false,
                            'isCascadePersist' => false,
                            'isCascadeRefresh' => false,
                            'isCascadeMerge' => false,
                            'isCascadeDetach' => false,
                            'sourceToTargetKeyColumns' => [
                                'pedido_id' => 'id',
                            ],
                            'joinColumnFieldNames' => [
                                'pedido_id' => 'pedido_id',
                            ],
                            'targetToSourceKeyColumns' => [
                                'id' => 'pedido_id',
                            ],
                            'orphanRemoval' => false,
                        ],
                        'producto' => [
                            'fieldName' => 'producto',
                            'joinColumns' => [
                                [
                                    'name' => 'producto_id',
                                    'referencedColumnName' => 'id',
                                ],
                            ],
                            'cascade' => [],
                            'inversedBy' => 'detalles',
                            'targetEntity' => 'App\\Entity\\Producto',
                            'fetch' => 2,
                            'type' => 2,
                            'mappedBy' => null,
                            'isOwningSide' => true,
                            'sourceEntity' => 'App\\Entity\\Detalle',
                            'isCascadeRemove' => false,
                            'isCascadePersist' => false,
                            'isCascadeRefresh' => false,
                            'isCascadeMerge' => false,
                            'isCascadeDetach' => false,
                            'sourceToTargetKeyColumns' => [
                                'producto_id' => 'id',
                            ],
                            'joinColumnFieldNames' => [
                                'producto_id' => 'producto_id',
                            ],
                            'targetToSourceKeyColumns' => [
                                'id' => 'producto_id',
                            ],
                            'orphanRemoval' => false,
                        ],
                    ],
                ],
                'idGenerator' => [
                    $o[1],
                ],
            ],
        ],
        $o[0],
        []
    );
},
2 => static function () {
    return \Symfony\Component\VarExporter\Internal\Hydrator::hydrate(
        $o = [
            clone (($p = &\Symfony\Component\VarExporter\Internal\Registry::$prototypes)['Doctrine\\ORM\\Mapping\\ClassMetadata'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\ClassMetadata')),
            clone ($p['Doctrine\\ORM\\Id\\IdentityGenerator'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Id\\IdentityGenerator')),
        ],
        null,
        [
            'stdClass' => [
                'name' => [
                    'App\\Entity\\Empresa',
                ],
                'namespace' => [
                    'App\\Entity',
                ],
                'rootEntityName' => [
                    'App\\Entity\\Empresa',
                ],
                'customRepositoryClassName' => [
                    'App\\Repository\\EmpresaRepository',
                ],
                'identifier' => [
                    [
                        'id',
                    ],
                ],
                'generatorType' => [
                    4,
                ],
                'fieldMappings' => [
                    [
                        'id' => [
                            'fieldName' => 'id',
                            'type' => 'integer',
                            'scale' => null,
                            'length' => null,
                            'unique' => false,
                            'nullable' => false,
                            'precision' => null,
                            'id' => true,
                            'columnName' => 'id',
                        ],
                        'username' => [
                            'fieldName' => 'username',
                            'type' => 'string',
                            'scale' => null,
                            'length' => 180,
                            'unique' => true,
                            'nullable' => false,
                            'precision' => null,
                            'columnName' => 'username',
                        ],
                        'roles' => [
                            'fieldName' => 'roles',
                            'type' => 'json',
                            'scale' => null,
                            'length' => null,
                            'unique' => false,
                            'nullable' => false,
                            'precision' => null,
                            'columnName' => 'roles',
                        ],
                        'password' => [
                            'fieldName' => 'password',
                            'type' => 'string',
                            'scale' => null,
                            'length' => null,
                            'unique' => false,
                            'nullable' => false,
                            'precision' => null,
                            'columnName' => 'password',
                        ],
                        'nombreEmpresa' => [
                            'fieldName' => 'nombreEmpresa',
                            'type' => 'string',
                            'scale' => null,
                            'length' => 100,
                            'unique' => false,
                            'nullable' => false,
                            'precision' => null,
                            'columnName' => 'nombre_empresa',
                        ],
                        'correoElectronico' => [
                            'fieldName' => 'correoElectronico',
                            'type' => 'string',
                            'scale' => null,
                            'length' => 100,
                            'unique' => false,
                            'nullable' => false,
                            'precision' => null,
                            'columnName' => 'correo_electronico',
                        ],
                        'codigoPostal' => [
                            'fieldName' => 'codigoPostal',
                            'type' => 'integer',
                            'scale' => null,
                            'length' => null,
                            'unique' => false,
                            'nullable' => false,
                            'precision' => null,
                            'columnName' => 'codigo_postal',
                        ],
                        'direccion' => [
                            'fieldName' => 'direccion',
                            'type' => 'string',
                            'scale' => null,
                            'length' => 200,
                            'unique' => false,
                            'nullable' => false,
                            'precision' => null,
                            'columnName' => 'direccion',
                        ],
                        'telefono' => [
                            'fieldName' => 'telefono',
                            'type' => 'integer',
                            'scale' => null,
                            'length' => null,
                            'unique' => false,
                            'nullable' => false,
                            'precision' => null,
                            'columnName' => 'telefono',
                        ],
                        'dni' => [
                            'fieldName' => 'dni',
                            'type' => 'string',
                            'scale' => null,
                            'length' => 9,
                            'unique' => false,
                            'nullable' => false,
                            'precision' => null,
                            'columnName' => 'dni',
                        ],
                        'logo' => [
                            'fieldName' => 'logo',
                            'type' => 'string',
                            'scale' => null,
                            'length' => 255,
                            'unique' => false,
                            'nullable' => true,
                            'precision' => null,
                            'columnName' => 'logo',
                        ],
                    ],
                ],
                'fieldNames' => [
                    [
                        'id' => 'id',
                        'username' => 'username',
                        'roles' => 'roles',
                        'password' => 'password',
                        'nombre_empresa' => 'nombreEmpresa',
                        'correo_electronico' => 'correoElectronico',
                        'codigo_postal' => 'codigoPostal',
                        'direccion' => 'direccion',
                        'telefono' => 'telefono',
                        'dni' => 'dni',
                        'logo' => 'logo',
                    ],
                ],
                'columnNames' => [
                    [
                        'id' => 'id',
                        'username' => 'username',
                        'roles' => 'roles',
                        'password' => 'password',
                        'nombreEmpresa' => 'nombre_empresa',
                        'correoElectronico' => 'correo_electronico',
                        'codigoPostal' => 'codigo_postal',
                        'direccion' => 'direccion',
                        'telefono' => 'telefono',
                        'dni' => 'dni',
                        'logo' => 'logo',
                    ],
                ],
                'table' => [
                    [
                        'name' => 'empresa',
                    ],
                ],
                'associationMappings' => [
                    [
                        'pedidos' => [
                            'fieldName' => 'pedidos',
                            'mappedBy' => 'empresa',
                            'targetEntity' => 'App\\Entity\\Pedido',
                            'cascade' => [],
                            'orphanRemoval' => false,
                            'fetch' => 2,
                            'type' => 4,
                            'inversedBy' => null,
                            'isOwningSide' => false,
                            'sourceEntity' => 'App\\Entity\\Empresa',
                            'isCascadeRemove' => false,
                            'isCascadePersist' => false,
                            'isCascadeRefresh' => false,
                            'isCascadeMerge' => false,
                            'isCascadeDetach' => false,
                        ],
                        'productos' => [
                            'fieldName' => 'productos',
                            'mappedBy' => 'empresa',
                            'targetEntity' => 'App\\Entity\\Producto',
                            'cascade' => [],
                            'orphanRemoval' => false,
                            'fetch' => 2,
                            'type' => 4,
                            'inversedBy' => null,
                            'isOwningSide' => false,
                            'sourceEntity' => 'App\\Entity\\Empresa',
                            'isCascadeRemove' => false,
                            'isCascadePersist' => false,
                            'isCascadeRefresh' => false,
                            'isCascadeMerge' => false,
                            'isCascadeDetach' => false,
                        ],
                        'clientes' => [
                            'fieldName' => 'clientes',
                            'mappedBy' => 'empresa',
                            'targetEntity' => 'App\\Entity\\Cliente',
                            'cascade' => [],
                            'orphanRemoval' => false,
                            'fetch' => 2,
                            'type' => 4,
                            'inversedBy' => null,
                            'isOwningSide' => false,
                            'sourceEntity' => 'App\\Entity\\Empresa',
                            'isCascadeRemove' => false,
                            'isCascadePersist' => false,
                            'isCascadeRefresh' => false,
                            'isCascadeMerge' => false,
                            'isCascadeDetach' => false,
                        ],
                    ],
                ],
                'idGenerator' => [
                    $o[1],
                ],
            ],
        ],
        $o[0],
        []
    );
},
3 => static function () {
    return \Symfony\Component\VarExporter\Internal\Hydrator::hydrate(
        $o = [
            clone (($p = &\Symfony\Component\VarExporter\Internal\Registry::$prototypes)['Doctrine\\ORM\\Mapping\\ClassMetadata'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\ClassMetadata')),
            clone ($p['Doctrine\\ORM\\Id\\IdentityGenerator'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Id\\IdentityGenerator')),
        ],
        null,
        [
            'stdClass' => [
                'name' => [
                    'App\\Entity\\Pedido',
                ],
                'namespace' => [
                    'App\\Entity',
                ],
                'rootEntityName' => [
                    'App\\Entity\\Pedido',
                ],
                'customRepositoryClassName' => [
                    'App\\Repository\\PedidoRepository',
                ],
                'identifier' => [
                    [
                        'id',
                    ],
                ],
                'generatorType' => [
                    4,
                ],
                'fieldMappings' => [
                    [
                        'id' => [
                            'fieldName' => 'id',
                            'type' => 'integer',
                            'scale' => null,
                            'length' => null,
                            'unique' => false,
                            'nullable' => false,
                            'precision' => null,
                            'id' => true,
                            'columnName' => 'id',
                        ],
                        'fecha' => [
                            'fieldName' => 'fecha',
                            'type' => 'date',
                            'scale' => null,
                            'length' => null,
                            'unique' => false,
                            'nullable' => false,
                            'precision' => null,
                            'columnName' => 'fecha',
                        ],
                        'estado' => [
                            'fieldName' => 'estado',
                            'type' => 'boolean',
                            'scale' => null,
                            'length' => null,
                            'unique' => false,
                            'nullable' => false,
                            'precision' => null,
                            'columnName' => 'estado',
                        ],
                        'nombrePedido' => [
                            'fieldName' => 'nombrePedido',
                            'type' => 'string',
                            'scale' => null,
                            'length' => 50,
                            'unique' => false,
                            'nullable' => false,
                            'precision' => null,
                            'columnName' => 'nombre_pedido',
                        ],
                    ],
                ],
                'fieldNames' => [
                    [
                        'id' => 'id',
                        'fecha' => 'fecha',
                        'estado' => 'estado',
                        'nombre_pedido' => 'nombrePedido',
                    ],
                ],
                'columnNames' => [
                    [
                        'id' => 'id',
                        'fecha' => 'fecha',
                        'estado' => 'estado',
                        'nombrePedido' => 'nombre_pedido',
                    ],
                ],
                'table' => [
                    [
                        'name' => 'pedido',
                    ],
                ],
                'associationMappings' => [
                    [
                        'empresa' => [
                            'fieldName' => 'empresa',
                            'joinColumns' => [
                                [
                                    'name' => 'empresa_id',
                                    'referencedColumnName' => 'id',
                                ],
                            ],
                            'cascade' => [],
                            'inversedBy' => 'pedidos',
                            'targetEntity' => 'App\\Entity\\Empresa',
                            'fetch' => 2,
                            'type' => 2,
                            'mappedBy' => null,
                            'isOwningSide' => true,
                            'sourceEntity' => 'App\\Entity\\Pedido',
                            'isCascadeRemove' => false,
                            'isCascadePersist' => false,
                            'isCascadeRefresh' => false,
                            'isCascadeMerge' => false,
                            'isCascadeDetach' => false,
                            'sourceToTargetKeyColumns' => [
                                'empresa_id' => 'id',
                            ],
                            'joinColumnFieldNames' => [
                                'empresa_id' => 'empresa_id',
                            ],
                            'targetToSourceKeyColumns' => [
                                'id' => 'empresa_id',
                            ],
                            'orphanRemoval' => false,
                        ],
                        'detalles' => [
                            'fieldName' => 'detalles',
                            'mappedBy' => 'pedido',
                            'targetEntity' => 'App\\Entity\\Detalle',
                            'cascade' => [],
                            'orphanRemoval' => false,
                            'fetch' => 2,
                            'type' => 4,
                            'inversedBy' => null,
                            'isOwningSide' => false,
                            'sourceEntity' => 'App\\Entity\\Pedido',
                            'isCascadeRemove' => false,
                            'isCascadePersist' => false,
                            'isCascadeRefresh' => false,
                            'isCascadeMerge' => false,
                            'isCascadeDetach' => false,
                        ],
                        'cliente' => [
                            'fieldName' => 'cliente',
                            'joinColumns' => [
                                [
                                    'name' => 'cliente_id',
                                    'referencedColumnName' => 'id',
                                ],
                            ],
                            'cascade' => [],
                            'inversedBy' => 'pedidos',
                            'targetEntity' => 'App\\Entity\\Cliente',
                            'fetch' => 2,
                            'type' => 2,
                            'mappedBy' => null,
                            'isOwningSide' => true,
                            'sourceEntity' => 'App\\Entity\\Pedido',
                            'isCascadeRemove' => false,
                            'isCascadePersist' => false,
                            'isCascadeRefresh' => false,
                            'isCascadeMerge' => false,
                            'isCascadeDetach' => false,
                            'sourceToTargetKeyColumns' => [
                                'cliente_id' => 'id',
                            ],
                            'joinColumnFieldNames' => [
                                'cliente_id' => 'cliente_id',
                            ],
                            'targetToSourceKeyColumns' => [
                                'id' => 'cliente_id',
                            ],
                            'orphanRemoval' => false,
                        ],
                    ],
                ],
                'idGenerator' => [
                    $o[1],
                ],
            ],
        ],
        $o[0],
        []
    );
},
4 => static function () {
    return \Symfony\Component\VarExporter\Internal\Hydrator::hydrate(
        $o = [
            clone (($p = &\Symfony\Component\VarExporter\Internal\Registry::$prototypes)['Doctrine\\ORM\\Mapping\\ClassMetadata'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\ClassMetadata')),
            clone ($p['Doctrine\\ORM\\Id\\IdentityGenerator'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Id\\IdentityGenerator')),
        ],
        null,
        [
            'stdClass' => [
                'name' => [
                    'App\\Entity\\Producto',
                ],
                'namespace' => [
                    'App\\Entity',
                ],
                'rootEntityName' => [
                    'App\\Entity\\Producto',
                ],
                'customRepositoryClassName' => [
                    'App\\Repository\\ProductoRepository',
                ],
                'identifier' => [
                    [
                        'id',
                    ],
                ],
                'generatorType' => [
                    4,
                ],
                'fieldMappings' => [
                    [
                        'id' => [
                            'fieldName' => 'id',
                            'type' => 'integer',
                            'scale' => null,
                            'length' => null,
                            'unique' => false,
                            'nullable' => false,
                            'precision' => null,
                            'id' => true,
                            'columnName' => 'id',
                        ],
                        'nombre' => [
                            'fieldName' => 'nombre',
                            'type' => 'string',
                            'scale' => null,
                            'length' => 200,
                            'unique' => false,
                            'nullable' => false,
                            'precision' => null,
                            'columnName' => 'nombre',
                        ],
                        'precio' => [
                            'fieldName' => 'precio',
                            'type' => 'float',
                            'scale' => null,
                            'length' => null,
                            'unique' => false,
                            'nullable' => false,
                            'precision' => null,
                            'columnName' => 'precio',
                        ],
                        'descripcion' => [
                            'fieldName' => 'descripcion',
                            'type' => 'string',
                            'scale' => null,
                            'length' => 255,
                            'unique' => false,
                            'nullable' => true,
                            'precision' => null,
                            'columnName' => 'descripcion',
                        ],
                    ],
                ],
                'fieldNames' => [
                    [
                        'id' => 'id',
                        'nombre' => 'nombre',
                        'precio' => 'precio',
                        'descripcion' => 'descripcion',
                    ],
                ],
                'columnNames' => [
                    [
                        'id' => 'id',
                        'nombre' => 'nombre',
                        'precio' => 'precio',
                        'descripcion' => 'descripcion',
                    ],
                ],
                'table' => [
                    [
                        'name' => 'producto',
                    ],
                ],
                'associationMappings' => [
                    [
                        'detalles' => [
                            'fieldName' => 'detalles',
                            'mappedBy' => 'producto',
                            'targetEntity' => 'App\\Entity\\Detalle',
                            'cascade' => [],
                            'orphanRemoval' => false,
                            'fetch' => 2,
                            'type' => 4,
                            'inversedBy' => null,
                            'isOwningSide' => false,
                            'sourceEntity' => 'App\\Entity\\Producto',
                            'isCascadeRemove' => false,
                            'isCascadePersist' => false,
                            'isCascadeRefresh' => false,
                            'isCascadeMerge' => false,
                            'isCascadeDetach' => false,
                        ],
                        'empresa' => [
                            'fieldName' => 'empresa',
                            'joinColumns' => [
                                [
                                    'name' => 'empresa_id',
                                    'referencedColumnName' => 'id',
                                ],
                            ],
                            'cascade' => [],
                            'inversedBy' => 'productos',
                            'targetEntity' => 'App\\Entity\\Empresa',
                            'fetch' => 2,
                            'type' => 2,
                            'mappedBy' => null,
                            'isOwningSide' => true,
                            'sourceEntity' => 'App\\Entity\\Producto',
                            'isCascadeRemove' => false,
                            'isCascadePersist' => false,
                            'isCascadeRefresh' => false,
                            'isCascadeMerge' => false,
                            'isCascadeDetach' => false,
                            'sourceToTargetKeyColumns' => [
                                'empresa_id' => 'id',
                            ],
                            'joinColumnFieldNames' => [
                                'empresa_id' => 'empresa_id',
                            ],
                            'targetToSourceKeyColumns' => [
                                'id' => 'empresa_id',
                            ],
                            'orphanRemoval' => false,
                        ],
                    ],
                ],
                'idGenerator' => [
                    $o[1],
                ],
            ],
        ],
        $o[0],
        []
    );
},

]];
