<?php

namespace Container799qPX1;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_CEyN0GQService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.cEyN0GQ' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.cEyN0GQ'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'detalle' => ['privates', '.errored..service_locator.cEyN0GQ.App\\Entity\\Detalle', NULL, 'Cannot autowire service ".service_locator.cEyN0GQ": it references class "App\\Entity\\Detalle" but no such service exists.'],
            'detalleRepository' => ['privates', 'App\\Repository\\DetalleRepository', 'getDetalleRepositoryService', true],
            'pedido' => ['privates', '.errored..service_locator.cEyN0GQ.App\\Entity\\Pedido', NULL, 'Cannot autowire service ".service_locator.cEyN0GQ": it references class "App\\Entity\\Pedido" but no such service exists.'],
            'pedidoRepository' => ['privates', 'App\\Repository\\PedidoRepository', 'getPedidoRepositoryService', true],
        ], [
            'detalle' => 'App\\Entity\\Detalle',
            'detalleRepository' => 'App\\Repository\\DetalleRepository',
            'pedido' => 'App\\Entity\\Pedido',
            'pedidoRepository' => 'App\\Repository\\PedidoRepository',
        ]);
    }
}
