<?php

namespace Container799qPX1;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_0uAfAyaService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.0uAfAya' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.0uAfAya'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'empresa' => ['privates', '.errored..service_locator.0uAfAya.Symfony\\Component\\Security\\Core\\User\\UserInterface', NULL, 'Cannot autowire service ".service_locator.0uAfAya": it references interface "Symfony\\Component\\Security\\Core\\User\\UserInterface" but no such service exists. Did you create a class that implements this interface?'],
            'producto' => ['privates', '.errored..service_locator.0uAfAya.App\\Entity\\Producto', NULL, 'Cannot autowire service ".service_locator.0uAfAya": it references class "App\\Entity\\Producto" but no such service exists.'],
        ], [
            'empresa' => 'Symfony\\Component\\Security\\Core\\User\\UserInterface',
            'producto' => 'App\\Entity\\Producto',
        ]);
    }
}
