<?php

namespace ContainerPQZd9tl;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_XHkoRuKService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.xHkoRuK' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.xHkoRuK'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'detalleRepository' => ['privates', 'App\\Repository\\DetalleRepository', 'getDetalleRepositoryService', true],
            'pedido' => ['privates', '.errored..service_locator.xHkoRuK.App\\Entity\\Pedido', NULL, 'Cannot autowire service ".service_locator.xHkoRuK": it references class "App\\Entity\\Pedido" but no such service exists.'],
        ], [
            'detalleRepository' => 'App\\Repository\\DetalleRepository',
            'pedido' => 'App\\Entity\\Pedido',
        ]);
    }
}
