<?php

namespace ContainerN9xxOmv;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_F9r8YoService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.f9r8_yo' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.f9r8_yo'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'empresa' => ['privates', '.errored..service_locator.f9r8_yo.App\\Entity\\Empresa', NULL, 'Cannot autowire service ".service_locator.f9r8_yo": it references class "App\\Entity\\Empresa" but no such service exists.'],
        ], [
            'empresa' => 'App\\Entity\\Empresa',
        ]);
    }
}
