<?php

namespace ContainerN9xxOmv;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPedidoService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.25pKLxc.App\Entity\Pedido' shared service.
     *
     * @return \App\Entity\Pedido
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.25pKLxc": it references class "App\\Entity\\Pedido" but no such service exists.');
    }
}
