<?php

namespace ContainerN9xxOmv;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getProducto2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.ZkUSPTZ.App\Entity\Producto' shared service.
     *
     * @return \App\Entity\Producto
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.ZkUSPTZ": it references class "App\\Entity\\Producto" but no such service exists.');
    }
}
