<?php

namespace ContainerKX4AEMW;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_G8GD_ULService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.g8GD.uL' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.g8GD.uL'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'detalleRepository' => ['privates', 'App\\Repository\\DetalleRepository', 'getDetalleRepositoryService', true],
            'pedidoRepository' => ['privates', 'App\\Repository\\PedidoRepository', 'getPedidoRepositoryService', true],
        ], [
            'detalleRepository' => 'App\\Repository\\DetalleRepository',
            'pedidoRepository' => 'App\\Repository\\PedidoRepository',
        ]);
    }
}
