<?php

namespace Proxies\__CG__\App\Entity;


/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Empresa extends \App\Entity\Empresa implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array<string, null> properties to be lazy loaded, indexed by property name
     */
    public static $lazyPropertiesNames = array (
);

    /**
     * @var array<string, mixed> default values of properties to be lazy loaded, with keys being the property names
     *
     * @see \Doctrine\Common\Proxy\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array (
);



    public function __construct(?\Closure $initializer = null, ?\Closure $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'App\\Entity\\Empresa' . "\0" . 'id', '' . "\0" . 'App\\Entity\\Empresa' . "\0" . 'username', '' . "\0" . 'App\\Entity\\Empresa' . "\0" . 'roles', '' . "\0" . 'App\\Entity\\Empresa' . "\0" . 'password', '' . "\0" . 'App\\Entity\\Empresa' . "\0" . 'nombreEmpresa', '' . "\0" . 'App\\Entity\\Empresa' . "\0" . 'correoElectronico', '' . "\0" . 'App\\Entity\\Empresa' . "\0" . 'codigoPostal', '' . "\0" . 'App\\Entity\\Empresa' . "\0" . 'direccion', '' . "\0" . 'App\\Entity\\Empresa' . "\0" . 'telefono', '' . "\0" . 'App\\Entity\\Empresa' . "\0" . 'dni', '' . "\0" . 'App\\Entity\\Empresa' . "\0" . 'logo', '' . "\0" . 'App\\Entity\\Empresa' . "\0" . 'pedidos', '' . "\0" . 'App\\Entity\\Empresa' . "\0" . 'productos', '' . "\0" . 'App\\Entity\\Empresa' . "\0" . 'clientes', '' . "\0" . 'App\\Entity\\Empresa' . "\0" . 'ciudad'];
        }

        return ['__isInitialized__', '' . "\0" . 'App\\Entity\\Empresa' . "\0" . 'id', '' . "\0" . 'App\\Entity\\Empresa' . "\0" . 'username', '' . "\0" . 'App\\Entity\\Empresa' . "\0" . 'roles', '' . "\0" . 'App\\Entity\\Empresa' . "\0" . 'password', '' . "\0" . 'App\\Entity\\Empresa' . "\0" . 'nombreEmpresa', '' . "\0" . 'App\\Entity\\Empresa' . "\0" . 'correoElectronico', '' . "\0" . 'App\\Entity\\Empresa' . "\0" . 'codigoPostal', '' . "\0" . 'App\\Entity\\Empresa' . "\0" . 'direccion', '' . "\0" . 'App\\Entity\\Empresa' . "\0" . 'telefono', '' . "\0" . 'App\\Entity\\Empresa' . "\0" . 'dni', '' . "\0" . 'App\\Entity\\Empresa' . "\0" . 'logo', '' . "\0" . 'App\\Entity\\Empresa' . "\0" . 'pedidos', '' . "\0" . 'App\\Entity\\Empresa' . "\0" . 'productos', '' . "\0" . 'App\\Entity\\Empresa' . "\0" . 'clientes', '' . "\0" . 'App\\Entity\\Empresa' . "\0" . 'ciudad'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Empresa $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy::$lazyPropertiesDefaults as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load(): void
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized(): bool
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized): void
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null): void
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer(): ?\Closure
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null): void
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner(): ?\Closure
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @deprecated no longer in use - generated code now relies on internal components rather than generated public API
     * @static
     */
    public function __getLazyProperties(): array
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId(): ?int
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function getUsername(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUsername', []);

        return parent::getUsername();
    }

    /**
     * {@inheritDoc}
     */
    public function setUsername(string $username): \App\Entity\Empresa
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUsername', [$username]);

        return parent::setUsername($username);
    }

    /**
     * {@inheritDoc}
     */
    public function getUserIdentifier(): string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUserIdentifier', []);

        return parent::getUserIdentifier();
    }

    /**
     * {@inheritDoc}
     */
    public function getRoles(): array
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRoles', []);

        return parent::getRoles();
    }

    /**
     * {@inheritDoc}
     */
    public function setRoles(array $roles): \App\Entity\Empresa
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setRoles', [$roles]);

        return parent::setRoles($roles);
    }

    /**
     * {@inheritDoc}
     */
    public function getPassword(): string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPassword', []);

        return parent::getPassword();
    }

    /**
     * {@inheritDoc}
     */
    public function setPassword(string $password): \App\Entity\Empresa
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPassword', [$password]);

        return parent::setPassword($password);
    }

    /**
     * {@inheritDoc}
     */
    public function eraseCredentials()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'eraseCredentials', []);

        return parent::eraseCredentials();
    }

    /**
     * {@inheritDoc}
     */
    public function getNombreEmpresa(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNombreEmpresa', []);

        return parent::getNombreEmpresa();
    }

    /**
     * {@inheritDoc}
     */
    public function setNombreEmpresa(string $nombreEmpresa): \App\Entity\Empresa
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNombreEmpresa', [$nombreEmpresa]);

        return parent::setNombreEmpresa($nombreEmpresa);
    }

    /**
     * {@inheritDoc}
     */
    public function getCorreoElectronico(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCorreoElectronico', []);

        return parent::getCorreoElectronico();
    }

    /**
     * {@inheritDoc}
     */
    public function setCorreoElectronico(string $correoElectronico): \App\Entity\Empresa
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCorreoElectronico', [$correoElectronico]);

        return parent::setCorreoElectronico($correoElectronico);
    }

    /**
     * {@inheritDoc}
     */
    public function getCodigoPostal(): ?int
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCodigoPostal', []);

        return parent::getCodigoPostal();
    }

    /**
     * {@inheritDoc}
     */
    public function setCodigoPostal(int $codigoPostal): \App\Entity\Empresa
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCodigoPostal', [$codigoPostal]);

        return parent::setCodigoPostal($codigoPostal);
    }

    /**
     * {@inheritDoc}
     */
    public function getDireccion(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDireccion', []);

        return parent::getDireccion();
    }

    /**
     * {@inheritDoc}
     */
    public function setDireccion(string $direccion): \App\Entity\Empresa
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDireccion', [$direccion]);

        return parent::setDireccion($direccion);
    }

    /**
     * {@inheritDoc}
     */
    public function getTelefono(): ?int
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTelefono', []);

        return parent::getTelefono();
    }

    /**
     * {@inheritDoc}
     */
    public function setTelefono(int $telefono): \App\Entity\Empresa
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTelefono', [$telefono]);

        return parent::setTelefono($telefono);
    }

    /**
     * {@inheritDoc}
     */
    public function getDni(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDni', []);

        return parent::getDni();
    }

    /**
     * {@inheritDoc}
     */
    public function setDni(string $dni): \App\Entity\Empresa
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDni', [$dni]);

        return parent::setDni($dni);
    }

    /**
     * {@inheritDoc}
     */
    public function getLogo(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLogo', []);

        return parent::getLogo();
    }

    /**
     * {@inheritDoc}
     */
    public function setLogo(?string $logo): \App\Entity\Empresa
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLogo', [$logo]);

        return parent::setLogo($logo);
    }

    /**
     * {@inheritDoc}
     */
    public function getPedidos(): \Doctrine\Common\Collections\Collection
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPedidos', []);

        return parent::getPedidos();
    }

    /**
     * {@inheritDoc}
     */
    public function addPedido(\App\Entity\Pedido $pedido): \App\Entity\Empresa
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addPedido', [$pedido]);

        return parent::addPedido($pedido);
    }

    /**
     * {@inheritDoc}
     */
    public function removePedido(\App\Entity\Pedido $pedido): \App\Entity\Empresa
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removePedido', [$pedido]);

        return parent::removePedido($pedido);
    }

    /**
     * {@inheritDoc}
     */
    public function __toString(): string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, '__toString', []);

        return parent::__toString();
    }

    /**
     * {@inheritDoc}
     */
    public function getProductos(): \Doctrine\Common\Collections\Collection
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getProductos', []);

        return parent::getProductos();
    }

    /**
     * {@inheritDoc}
     */
    public function addProducto(\App\Entity\Producto $producto): \App\Entity\Empresa
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addProducto', [$producto]);

        return parent::addProducto($producto);
    }

    /**
     * {@inheritDoc}
     */
    public function removeProducto(\App\Entity\Producto $producto): \App\Entity\Empresa
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeProducto', [$producto]);

        return parent::removeProducto($producto);
    }

    /**
     * {@inheritDoc}
     */
    public function getClientes(): \Doctrine\Common\Collections\Collection
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getClientes', []);

        return parent::getClientes();
    }

    /**
     * {@inheritDoc}
     */
    public function addCliente(\App\Entity\Cliente $cliente): \App\Entity\Empresa
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addCliente', [$cliente]);

        return parent::addCliente($cliente);
    }

    /**
     * {@inheritDoc}
     */
    public function removeCliente(\App\Entity\Cliente $cliente): \App\Entity\Empresa
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeCliente', [$cliente]);

        return parent::removeCliente($cliente);
    }

    /**
     * {@inheritDoc}
     */
    public function getCiudad(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCiudad', []);

        return parent::getCiudad();
    }

    /**
     * {@inheritDoc}
     */
    public function setCiudad(string $ciudad): \App\Entity\Empresa
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCiudad', [$ciudad]);

        return parent::setCiudad($ciudad);
    }

}
