<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerCDCuDiH\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerCDCuDiH/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerCDCuDiH.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerCDCuDiH\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerCDCuDiH\App_KernelDevDebugContainer([
    'container.build_hash' => 'CDCuDiH',
    'container.build_id' => 'faf22a70',
    'container.build_time' => 1651785826,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerCDCuDiH');
