<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerPQZd9tl\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerPQZd9tl/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerPQZd9tl.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerPQZd9tl\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerPQZd9tl\App_KernelDevDebugContainer([
    'container.build_hash' => 'PQZd9tl',
    'container.build_id' => '436da633',
    'container.build_time' => 1653337400,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerPQZd9tl');
