<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerZyOIRHL\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerZyOIRHL/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerZyOIRHL.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerZyOIRHL\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerZyOIRHL\App_KernelDevDebugContainer([
    'container.build_hash' => 'ZyOIRHL',
    'container.build_id' => 'be814c8e',
    'container.build_time' => 1653418095,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerZyOIRHL');
